### PR TITLE
[Chapter 7] Added faster code for DataFrames

### PR DESCRIPTION
**Pull request by AdityaKane2001**
@DavidLandup0 

The current code in Chapter 7 for getting a single DataFrame is a bit slow, and it takes a lot of time on Kaggle to execute. I have refactored it a bit and the speedup is a bit more than 5x. The old code needed 10.427 seconds for 500 records whereas the new code needs only 1.84 seconds for the same.

PS. Please enable [Notebook Review](https://github.com/marketplace/review-notebook-app) app on the repo to make notebook reviews easier.

### CODE REVIEW

**Comment by DavidLandup0** [comment]
Thank you for the PR! Verified - the runtimes are reproducible, thanks!
Before merging, could you replace:

```
for index, path in enumerate(data[:500]):
```

With:

```
for index, path in enumerate(data):
```

Because some other cells depend on the data (and the example was made to show how someone can get _all_ patients in a single DF).

Also, `patient_id = split[0].split('/')[1]` -> `split[0].split(os.sep)[1]`, since the separator is OS-dependent.

**Review by DavidLandup0 — CHANGES_REQUESTED** [review]
Noted in the last comment

**Comment by AdityaKane2001** [comment]
@DavidLandup0 

Done.

**Comment by DavidLandup0** [comment]
Merged, thanks for pointing this out!

**Pull request merged**
